language: d

d:
  - dmd-2.088.0
  - dmd-2.078.2

services:
  - mongodb

addons:
  apt:
    packages:
      - pkg-config
      - zlib1g-dev
      - libevent-dev
      - libssl-dev

sudo: false

script:
  - dub upgrade --missing-only # attempt to work around DUB build issue
  - dub test
